mqtt:
  host: "mqtt.nmatsui.work"
  port: 8883
  cafile: "/home/ubuntu/ros_ws/src/turtlesim_operator/secrets/ca.crt"
  username: "turtlesim"
  password: ""
  topics:
    - key: "command_sender"
      # name: "/ros/turtle/cmd"
      name: "/controller/cmd"
    - key: "attribute_receiver"
      name: "/ros/turtle/temperature"
ros:
  topics:
    - key: "turtlesim"
      name: "/turtle1/cmd_vel"
    - key: "temperature"
      name: "/turtle1/temperature"
